# Generated by Django 4.0.3 on 2022-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='github',
            field=models.CharField(default='https://github.com/ignorecrowd/DSA', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=555),
        ),
    ]
