# Generated by Django 4.0.3 on 2022-05-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_github_alter_work_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='date',
            new_name='endDate',
        ),
        migrations.AddField(
            model_name='work',
            name='startDate',
            field=models.CharField(default='25 June 2003', max_length=255),
            preserve_default=False,
        ),
    ]
