# Generated by Django 4.0.3 on 2022-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='django-portfolio\\www\\public/resume'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
