# Generated by Django 4.0.3 on 2022-05-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_resume_resume_alter_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.FileField(default='', upload_to='django-portfolio\\www\\public/img'),
            preserve_default=False,
        ),
    ]
