# Generated by Django 4.0.3 on 2022-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_remove_work_image_work_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='type',
        ),
        migrations.AddField(
            model_name='work',
            name='tag1',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='tag2',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='tag3',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='tag4',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='tag5',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='tag6',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='endDate',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='work',
            name='github',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='work',
            name='startDate',
            field=models.CharField(max_length=55),
        ),
    ]
