# Generated by Django 4.0.3 on 2022-06-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_remove_work_type_work_tag1_work_tag2_work_tag3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tag1',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='work',
            name='tag2',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='work',
            name='tag3',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='work',
            name='tag4',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='work',
            name='tag5',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='work',
            name='tag6',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
