# Generated by Django 4.0.3 on 2022-05-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFindMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=555)),
                ('working_time', models.CharField(max_length=555)),
                ('call_me', models.CharField(max_length=555)),
                ('email', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='ContactParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=555)),
            ],
        ),
    ]
