# Generated by Django 4.0.3 on 2022-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactfindme_contactparagraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactfindme',
            name='call_me',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='contactfindme',
            name='email',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='contactfindme',
            name='location',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='contactfindme',
            name='working_time',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='contactparagraph',
            name='paragraph',
            field=models.CharField(max_length=1200),
        ),
    ]
