# Generated by Django 4.0.3 on 2022-06-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timeStamp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
