# Generated by Django 4.0.3 on 2022-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=False),
        ),
    ]
