# Generated by Django 4.0.3 on 2022-06-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_tag1_blog_tag2_blog_tag3_blog_tag4_blog_tag5'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag6',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
