# Generated by Django 4.0.3 on 2022-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_blog_tag6'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1550),
        ),
    ]
