# Generated by Django 4.0.3 on 2022-05-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutParagraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paraone', models.CharField(max_length=555)),
                ('paratwo', models.CharField(max_length=555)),
                ('parathree', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillonename', models.CharField(max_length=50)),
                ('skilltwoname', models.CharField(max_length=50)),
                ('skillthreename', models.CharField(max_length=50)),
                ('skillfourname', models.CharField(max_length=50)),
                ('skillfivename', models.CharField(max_length=50)),
                ('skillsixname', models.CharField(max_length=50)),
                ('skillsevenname', models.CharField(max_length=50)),
                ('skilleightname', models.CharField(max_length=50)),
                ('skillone', models.CharField(max_length=8)),
                ('skilltwo', models.CharField(max_length=8)),
                ('skillthree', models.CharField(max_length=8)),
                ('skillfour', models.CharField(max_length=8)),
                ('skillfive', models.CharField(max_length=8)),
                ('skillsix', models.CharField(max_length=8)),
                ('skillseven', models.CharField(max_length=8)),
                ('skilleight', models.CharField(max_length=8)),
            ],
        ),
    ]
