# Generated by Django 4.0.3 on 2022-05-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutparagraphs_aboutskills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutParagraphs',
            new_name='AboutParagraph',
        ),
        migrations.RenameModel(
            old_name='AboutSkills',
            new_name='AboutSkill',
        ),
    ]
