# Generated by Django 4.0.3 on 2022-05-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_paraone_aboutparagraph_paragraph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutskill',
            old_name='skilleightname',
            new_name='skillleftname',
        ),
        migrations.RenameField(
            model_name='aboutskill',
            old_name='skilleight',
            new_name='skillleftvalue',
        ),
        migrations.RenameField(
            model_name='aboutskill',
            old_name='skillfivename',
            new_name='skillrightname',
        ),
        migrations.RenameField(
            model_name='aboutskill',
            old_name='skillfive',
            new_name='skillrightvalue',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillfour',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillfourname',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillone',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillonename',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillseven',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillsevenname',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillsix',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillsixname',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillthree',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skillthreename',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skilltwo',
        ),
        migrations.RemoveField(
            model_name='aboutskill',
            name='skilltwoname',
        ),
    ]
