# Generated by Django 4.0.3 on 2022-05-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_skilleightname_aboutskill_skillleftname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutskill',
            old_name='skillleftname',
            new_name='skill_left_name',
        ),
        migrations.RenameField(
            model_name='aboutskill',
            old_name='skillleftvalue',
            new_name='skill_left_value',
        ),
        migrations.RenameField(
            model_name='aboutskill',
            old_name='skillrightname',
            new_name='skill_right_name',
        ),
        migrations.RenameField(
            model_name='aboutskill',
            old_name='skillrightvalue',
            new_name='skill_right_value',
        ),
    ]
