# Generated by Django 4.0.3 on 2022-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_rename_skillleftname_aboutskill_skill_left_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='paragraph',
            field=models.CharField(max_length=1200),
        ),
    ]
